data<-read.table(file="therm.txt")
par(mfrow=c(4,1))
k1=data[,1]=="CACT"
k2=data[,1]=="CCAA"
k3=data[,1]=="CATC"
k4=data[,1]=="CTGG"
hist(data[k1,3],col=1,xlab="",nclass=100,main="",ylim=c(0,s))
hist(data[k2,3],col=2,xlab="",nclass=100,main="",ylim=c(0,s))
hist(data[k3,3],col=3,xlab="",nclass=100,main="",ylim=c(0,s))
hist(data[k4,3],col=4,xlab="",nclass=100,main="",ylim=c(0,s))
